### ISSUE TITLE
No mention of sanitization in README

### ISSUE THREAD

**Issue by soypat** [cristalhq/builq#14]
Maybe worth noting in the README:
* what kind of sanitizing is done to inputs
* If there is sanitization at all (I don't think I was able to find any at a glance)
* If the library is safe or not safe, what environment is it envisioned for: maybe only for when the programmer is constructing the queries, not for external inputs

**Comment by cristaloleg** [comment]
Thanks for the issue. Will be mentioned in GUIDE.md.

In short: no sanitization is done 'cause params don't appear in the query (if they are passed by %$ or %?)

**Comment by pellared** [comment]
I suggest moving these details to README.md
1. GUIDE.md does not suggest that implementation details are there
2. README.md is rendered in pkg.go.dev

**Comment by cristaloleg** [comment]
See https://github.com/cristalhq/builq/pull/15
